In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [2]:
data=pd.read_excel("university.xlsx")

In [3]:
data.head()

University   SAT  Top10  Accept  SFRatio  \
0                     Harvard University  1310     89      22       13   
1     California Institute of Technology  1415    100      25        6   
2  Massachusetts Institute of Technology  1260     62      59        9   
3                    Stanford University  1310     76      24       12   
4                   Princeton University  1280     83      33       13   

   Expenses  GradRate  
0     22704        94  
1     63575        81  
2     25026        72  
3     31510        88  
4     21864        90

In [4]:
data.shape

(100, 7)

In [5]:
data.isnull().sum()

University    0
SAT           0
Top10         0
Accept        0
SFRatio       0
Expenses      0
GradRate      0
dtype: int64

In [7]:
data=data.iloc[:,1:]
data.head()

SAT  Top10  Accept  SFRatio  Expenses  GradRate
0  1310     89      22       13     22704        94
1  1415    100      25        6     63575        81
2  1260     62      59        9     25026        72
3  1310     76      24       12     31510        88
4  1280     83      33       13     21864        90

In [8]:
from sklearn.preprocessing import scale,normalize

In [10]:
data1=scale(data)

C:\Users\Akhilesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64 were all converted to float64 by the scale function.
  """Entry point for launching an IPython kernel.


In [11]:
data1

array([[ 6.32860277e-01,  1.50011672e+00, -8.47758804e-01,
        -1.06559813e+00, -1.49953373e+00,  1.21638361e+00],
       [ 2.80231274e+00,  3.69443640e+00, -3.36033168e-01,
        -2.18224287e+00,  1.29812886e+00, -1.28171859e+00],
       [-4.00212326e-01, -3.88594066e+00,  5.46352405e+00,
        -1.70368084e+00, -1.34059041e+00, -3.01117396e+00],
       [ 6.32860277e-01, -1.09317017e+00, -5.06608380e-01,
        -1.22511881e+00, -8.96753843e-01,  6.34133635e-02],
       [ 1.30167148e-02,  3.03215082e-01,  1.02856853e+00,
        -1.06559813e+00, -1.55703261e+00,  4.47736779e-01],
       [ 1.45931836e+00, -4.94719345e-01, -8.47758804e-01,
         1.64625339e+00, -1.56606814e+00, -3.20910052e-01],
       [ 2.49239096e+00,  5.02698689e-01, -3.36033168e-01,
         5.29608650e-01,  4.98073064e-01,  8.32060194e-01],
       [ 1.25270384e+00, -6.94202952e-01, -3.36033168e-01,
        -1.08474061e-01, -1.22169095e+00, -8.97395175e-01],
       [-1.24733186e+00, -8.93686559e-01, -1.530

In [51]:
data2=normalize(data1)

In [52]:
data2

array([[5.76023081e-02, 3.91343925e-03, 9.67367005e-04, 5.71625958e-04,
        9.98322750e-01, 4.13329539e-03],
       [2.22516183e-02, 1.57255253e-03, 3.93138133e-04, 9.43531519e-05,
        9.99750272e-01, 1.27376755e-03],
       [5.02834427e-02, 2.47426464e-03, 2.35454216e-03, 3.59167448e-04,
        9.98724949e-01, 2.87333958e-03],
       [4.15379241e-02, 2.40983377e-03, 7.61000137e-04, 3.80500068e-04,
        9.99129763e-01, 2.79033384e-03],
       [5.84426668e-02, 3.78964168e-03, 1.50672500e-03, 5.93558335e-04,
        9.98273803e-01, 4.10925001e-03],
       [6.19998797e-02, 3.62814111e-03, 1.01036841e-03, 1.37777510e-03,
        9.98060285e-01, 3.94962196e-03],
       [2.69718106e-02, 1.61830864e-03, 4.81639476e-04, 4.43108318e-04,
        9.99633099e-01, 1.77243327e-03],
       [5.00059974e-02, 2.91079686e-03, 9.32947713e-04, 7.09040262e-04,
        9.98739185e-01, 3.09738641e-03],
       [2.76736953e-02, 1.74805131e-03, 4.08635370e-04, 5.44847160e-04,
        9.99612923e-01, 

In [53]:
from sklearn.decomposition import PCA

In [54]:
model=PCA()

In [55]:
model.fit(data2)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [56]:
model.components_

array([[ 0.99470736,  0.06401448,  0.02195063,  0.01625341, -0.03777804,
         0.06546924],
       [ 0.048057  , -0.39309496,  0.68802051, -0.39041272,  0.02416708,
        -0.46560553],
       [ 0.07754931, -0.315787  , -0.65794589, -0.02951572, -0.05965588,
        -0.67597476],
       [-0.01064809,  0.35585675, -0.2353027 , -0.89823183, -0.02245049,
         0.1027657 ],
       [ 0.02263019, -0.78363664, -0.18714421, -0.19900396,  0.03754436,
         0.55620713],
       [-0.04010463, -0.03060477,  0.05350557,  0.00442247, -0.99625115,
         0.04534554]])

In [57]:
#convert 1D to 2D
componet=pd.DataFrame(model.components_)

In [58]:
componet.head()

0         1         2         3         4         5
0  0.994707  0.064014  0.021951  0.016253 -0.037778  0.065469
1  0.048057 -0.393095  0.688021 -0.390413  0.024167 -0.465606
2  0.077549 -0.315787 -0.657946 -0.029516 -0.059656 -0.675975
3 -0.010648  0.355857 -0.235303 -0.898232 -0.022450  0.102766
4  0.022630 -0.783637 -0.187144 -0.199004  0.037544  0.556207

In [59]:
value=model.explained_variance_ratio_

In [60]:
value

array([9.99236689e-01, 3.11409160e-04, 1.71046352e-04, 1.52765823e-04,
       9.76970639e-05, 3.03929086e-05])

In [61]:
value.sum()

0.9999999999999999